version: "3.3"

services:
  nginx:
    container_name: ${NAME}
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.default-${NAME}.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.default-${NAME}.priority=100"
      - "traefik.http.routers.default-${NAME}.entrypoints=http"
      - "traefik.http.routers.secure-${NAME}.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.secure-${NAME}.priority=100"
      - "traefik.http.routers.secure-${NAME}.entrypoints=https"
      - "traefik.http.routers.secure-${NAME}.tls.certresolver=letsencrypt"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
    name: traefik

